#!/bin/sh

uci set wireless.radio0.disabled=0
uci set wireless.radio1.disabled=0
uci set wireless.default_radio0.ssid=DAM-AP410-2G
uci set wireless.default_radio1.ssid=DAM-AP410-5G
uci set wireless.default_radio0.encryption=none
uci set wireless.default_radio0.disabled=0
uci set wireless.default_radio1.encryption=none
uci set wireless.default_radio1.disabled=0
uci commit wireless

exit 0