#!/bin/sh

. /lib/functions/system.sh

wifi_base_mac="$(macaddr_random)"

uci set wireless.radio0.disabled='0'
uci set wireless.radio1.disabled='0'
uci set wireless.radio2.disabled='0'
uci set wireless.radio0.country='US'
uci set wireless.radio1.country='US'
uci set wireless.radio2.country='US'
uci set wireless.radio2.channel='37'
uci set wireless.radio2.reg_power_type='2'
uci set wireless.default_radio0.ssid='EHR330-2G'
uci set wireless.default_radio1.ssid='EHR330-5G'
uci set wireless.default_radio2.ssid='EHR330-6G'
uci set wireless.default_radio0.macaddr="$(macaddr_add "$wifi_base_mac" 0)"
uci set wireless.default_radio1.macaddr="$(macaddr_add "$wifi_base_mac" 1)"
uci set wireless.default_radio2.macaddr="$(macaddr_add "$wifi_base_mac" 2)"
uci set wireless.default_radio0.encryption='none'
uci set wireless.default_radio1.encryption='none'
uci set wireless.default_radio2.encryption='owe'
uci set wireless.default_radio0.disabled='0'
uci set wireless.default_radio1.disabled='0'
uci set wireless.default_radio2.disabled='0'
uci commit wireless

exit 0